spring.application.name=RemiPreparateur
spring.datasource.url=jdbc:postgresql://localhost:5433/remi_preparateur
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8080
python.api.url=http://localhost:8000
